import sys
import os
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import streamlit as st
from datetime import datetime
from bukid.crew import run_research, run_schedule
from chart import render_gantt, render_price_table
from bukid.models.models import VegetableScheduleOutput


#from dotenv import load_dotenv
#load_dotenv()

# Works both locally and in production
os.environ["MODEL"] = st.secrets.get("MODEL", "")
os.environ["ANTHROPIC_API_KEY"] = st.secrets.get("ANTHROPIC_API_KEY", "")

#from crewai.agents.agent_builder.base_agent_executor_mixin import CrewAgentExecutorMixin




# ── Page config ──────────────────────────────────────────────
st.set_page_config(page_title="🌱 Home Gardening Assistant", page_icon="🌱")
st.title("🌱 Home Gardening Assistant")
st.caption("Your AI-powered gardening crew!")


# ── Step 1: Get location ──────────────────────────────────────
if "location" not in st.session_state:
    st.session_state.location = None

if not st.session_state.location:
    with st.form("location_form"):
        st.subheader("Where is your garden located?")
        location = st.text_input("📍 Enter your city or region (e.g. Manila, Philippines)")
        submitted = st.form_submit_button("Start")

        if submitted and location.strip():
            st.session_state.location = location.strip()
            st.rerun()
        elif submitted:
            st.warning("Please enter your location to continue.")
    st.stop()

st.success(f"📍 Garden location: {st.session_state.location}")

# ── Step 2: Initialize session state ─────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = []
if "research_done" not in st.session_state:
    st.session_state.research_done = False
if "vegetables" not in st.session_state:
    st.session_state.vegetables = None
if "awaiting_confirmation" not in st.session_state:
    st.session_state.awaiting_confirmation = False
if "awaiting_feedback" not in st.session_state:
    st.session_state.awaiting_feedback = False
if "schedule_output" not in st.session_state:
    st.session_state.schedule_output = None


# ── Step 3: Display chat history ──────────────────────────────
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# ── Step 3b: Re-render chart if it exists ─────────────────────
if st.session_state.get("schedule_output"):
    schedule = st.session_state.schedule_output
    st.markdown(f"📝 {schedule.notes}")
    st.markdown(f"*Generated by {schedule.generated_by} on {schedule.timestamp}*")
    render_gantt(schedule)
    render_price_table(schedule)


# ── Step 4: Run Agent 1 automatically on first load ──────────
if not st.session_state.research_done:
    with st.chat_message("assistant"):
        with st.spinner("Finding the best vegetables for your area..."):
            previous_year = str(datetime.now().year - 2)
            result = run_research(st.session_state.location, previous_year)

        st.session_state.vegetables = result
        st.session_state.research_done = True

        follow_up = "\n\n---\n💬 **Are you happy with these vegetables? You can also add any vegetables you'd like to include!**"
        full_message = result + follow_up
        st.markdown(full_message)
        st.session_state.awaiting_feedback = True

    st.session_state.messages.append({"role": "assistant", "content": full_message})
    st.rerun()

# ── Step 4b: Handle vegetable feedback ───────────────────────
if st.session_state.get("awaiting_feedback"):
    if prompt := st.chat_input("Type any vegetables to add, or 'done' if you're happy with the list..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        if prompt.strip().lower() == "done":
            # User is happy, move on to schedule confirmation
            st.session_state.awaiting_feedback = False
            msg = "Great! **Would you like me to create a planting schedule for these vegetables?** (yes / no)"
            with st.chat_message("assistant"):
                st.markdown(msg)
            st.session_state.messages.append({"role": "assistant", "content": msg})
            st.session_state.awaiting_confirmation = True

        else:
            # Append user's vegetables to the list
            st.session_state.vegetables += f"\n\nAdditional vegetables requested by user: {prompt}"
            msg = f"Got it! I've added **{prompt}** to your list. 🌱 Any more to add, or type **'done'** to continue?"
            with st.chat_message("assistant"):
                st.markdown(msg)
            st.session_state.messages.append({"role": "assistant", "content": msg})

        st.rerun()
    st.stop() 

# ── Step 5: Handle user reply ─────────────────────────────────
if st.session_state.awaiting_confirmation:
    if prompt := st.chat_input("Type yes to get a schedule, or no to stop..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        if prompt.strip().lower() in ["yes", "y"]:
            st.session_state.awaiting_confirmation = False
            with st.chat_message("assistant"):
                with st.spinner("Creating your planting schedule..."):
                    schedule = run_schedule(
                        location=st.session_state.location,
                        vegetables=st.session_state.vegetables
                    )
                st.session_state.schedule_output = schedule  # 👈 save it to session state

            st.session_state.messages.append({"role": "assistant", "content": "📊 Here's your planting schedule!"})
            st.rerun()


        else:
            st.session_state.awaiting_confirmation = False
            msg = "No problem! Feel free to ask me anything else about your garden. 🌿"
            with st.chat_message("assistant"):
                st.markdown(msg)
            st.session_state.messages.append({"role": "assistant", "content": msg})

        st.rerun()
    st.stop() 

# ── Step 6: Open chat after flow is complete ──────────────────
elif st.session_state.research_done and not st.session_state.awaiting_confirmation:
    if prompt := st.chat_input("Ask me anything about your garden..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                result = run_research(st.session_state.location, str(datetime.now().year - 2))
            st.markdown(result)
        st.session_state.messages.append({"role": "assistant", "content": result})
        st.rerun()